#!/bin/bash
set -eu
: ${MONGO_HOST:=mongo}
: ${MONGO_PORT:=27017}
: ${MONGO_DB:=registry}
: ${MONGO_USER:=registry}
: ${MONGO_PASSWORD:=registry}

fail_counter=0

echo "Waiting for MongoDB"

until nc -z "$MONGO_HOST" "$MONGO_PORT"; do
    if [[ $fail_counter -gt 100 ]]; then
        >&2 echo 'Exceed max retries' && exit 1
    fi
    sleep 5
done
echo ""
