#!/bin/bash
set -eu
: ${MONGO_URL:=mongodb://mongo/registry}
: ${HARVEST_INIT:=false}

echo "Setting up harvest directory"
chown harvest:harvest /data

if [[ $HARVEST_INIT == "true" ]]; then
    echo "Harvesting"
    exec /sbin/setuser harvest catalog-harvest -s "${MONGO_URL}" -d /data -v
fi
