#!/bin/bash
set -eu
: ${MONGO_URL:=mongodb://mongo/registry}
: ${CRON_STRING:=0 0 * * *}
: ${ENABLE_CRON:=false}

if [[ "$ENABLE_CRON" == "true" ]]; then
    echo "Enabling CRON"

    echo "${CRON_STRING} harvest PATH="$PATH:/usr/local/bin" catalog-harvest -s \"${MONGO_URL}\" -d /data -v -f >> /var/log/harvest/harvest.log 2>&1" > /etc/crontab
fi

echo "Ready"
